name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: docker://rafaelcalleja/dind-buster:v0.1.8
      options: --privileged
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      sha: ${{ steps.updatev.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute next SemVer tag
        id: release
        run: |
          export VERSION=$(docker run --rm alpine/semver semver -c -i patch $(cat VERSION))
          echo $VERSION > VERSION
          echo ::debug ::relase version ${VERSION}
          echo ::set-output name=tag_name::${VERSION}
      - name: Update version
        id: updatev
        run: |
           git config user.name  github-actions
           git config user.email github-actions@github.com
           git add VERSION
           git commit -m "bump version"
           git push
           echo ::set-output name=sha::$(git rev-parse --short HEAD)
           curl --request POST \
                --url https://api.github.com/repos/${{ github.repository }}/releases \
                --header "Accept: application/vnd.github.v3+json" \
                --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                --header 'content-type: application/json' \
                --data '{
                    "tag_name": "v${{ steps.release.outputs.tag_name }}",
                    "body": "docker pull rafaelcalleja/keda-upstream-deployment-scaler:${{ steps.release.outputs.tag_name }}",
                    "name": "Release ${{ steps.release.outputs.tag_name }}",
                    "draft": false,
                    "prerelease": false
                }'
           exit $?
